######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 31 17:01:48 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += utc.h
FORMS += utc.ui
SOURCES += tests_checker.cpp utc.cpp
